# The repository from which we're fetching our rubygems.
source 'http://rubygems.org'

# Use guard for filesystem listening
gem 'guard', require: false

# For better mac filesystem listening performance
gem 'rb-fsevent', require: false
